apiVersion: v1
kind: Service

metadata:
  name: flask-service
  namespace: djangoapplication

spec:
  type: NodePort
  selector:
    app: flask-apps
  ports:
    - port: 8080
      targetPort: 5000
      nodePort: 30007
  type:
    LoadBalancer
