name: Deploy to AKS
on:
  push:
    branches:
      - master
      
env:
 
  RESOURCE_GROUP: "aks_rg"
  CLUSTER_NAME: "my-kubes"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
  
    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          deployment.yaml
          service.yaml
        namespace: default
